# Generated by Django 4.1.2 on 2022-10-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('miesiac_urodzenia', models.CharField(choices=[('I', 'styczeń'), ('II', 'luty'), ('III', 'marzec'), ('IV', 'kwiecień'), ('V', 'maj'), ('VI', 'czerwiec'), ('VII', 'lipiec'), ('VIII', 'sierpień'), ('XI', 'wrzesień'), ('X', 'październik'), ('XI', 'listopad'), ('XII', 'grudzień')], max_length=4)),
            ],
        ),
    ]
