# Generated by Django 4.1.2 on 2022-10-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class3app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='miesiac_urodzenia',
            field=models.CharField(choices=[('I', 'styczeń'), ('II', 'luty'), ('III', 'marzec'), ('IV', 'kwiecień'), ('V', 'maj'), ('VI', 'czerwiec'), ('VII', 'lipiec'), ('VIII', 'sierpień'), ('XI', 'wrzesień'), ('X', 'październik'), ('XI', 'listopad'), ('XII', 'grudzień')], default=('I', 'styczeń'), max_length=4),
        ),
    ]
