# Generated by Django 4.1.2 on 2022-10-19 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('class3app', '0002_alter_osoba_miesiac_urodzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
