# Generated by Django 4.1.2 on 2022-10-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class3app', '0004_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
