# Generated by Django 4.1.2 on 2022-11-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class3app', '0006_druzyna_osoba_druzyna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='druzyna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='class3app.druzyna', verbose_name='Drużyna'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miesiac_urodzenia',
            field=models.CharField(choices=[('I', 'Styczeń'), ('II', 'Luty'), ('III', 'Marzec'), ('IV', 'Kwiecień'), ('V', 'Maj'), ('VI', 'Czerwiec'), ('VII', 'Lipiec'), ('VIII', 'Sierpień'), ('IX', 'Wrzesień'), ('X', 'Październik'), ('XI', 'Listopad'), ('XII', 'Grudzień')], default='II', max_length=4),
        ),
    ]
