# Generated by Django 4.0.3 on 2022-11-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class3app', '0008_osoba_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_osoba', 'Pozwala przypisać inną osobę do obiektu Person.')]},
        ),
    ]
