# Generated by Django 4.0.3 on 2022-11-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class3app', '0011_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_osobas', 'pozwalaj wyświetlać obiekty modelu Osoba, których zalogowany użytkownik nie jest właścicielem.')]},
        ),
    ]
