# Generated by Django 4.1.3 on 2022-11-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete'], 'verbose_name_plural': 'Zadania'},
        ),
    ]
