# Generated by Django 4.1.3 on 2022-11-29 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDoList', '0002_alter_task_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
