# Generated by Django 4.1.3 on 2022-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0005_task_year_in_school_alter_task_responsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Zadania'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='task',
            name='completeStatus',
            field=models.CharField(choices=[('IDE', 'Ideas'), ('TD', 'To do'), ('DN', 'Done'), ('NS', 'Not started yet')], default='NS', max_length=3),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(choices=[('WK', 'Work'), ('EVE', 'Event'), ('HW', 'HouseWork'), ('BIL', 'Bills'), ('PER', 'Personal'), ('GR', 'Group'), ('STU', 'Studies'), ('HEA', 'Health'), ('DEF', 'General')], default='DEF', max_length=3),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Important and urgent'), (2, 'Not urgent but important'), (3, 'Urgent but not important'), (4, 'Not urgent and not important'), (5, 'Neither')], default=5),
        ),
    ]
