# Generated by Django 4.1.3 on 2022-11-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0006_alter_task_options_remove_task_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completeStatus',
            new_name='complete_status',
        ),
    ]
