# Generated by Django 4.1.3 on 2022-12-07 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDoList', '0009_alter_task_deadline_alter_task_responsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['created'], 'verbose_name_plural': 'Listy'},
        ),
        migrations.AddField(
            model_name='list',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoList.list'),
        ),
    ]
