# Generated by Django 4.1.3 on 2022-12-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0011_alter_task_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['name'], 'verbose_name_plural': 'Listy'},
        ),
        migrations.RemoveField(
            model_name='list',
            name='author',
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoList.list'),
        ),
    ]
